ledgers = ["bitcoin", "ethereum"]

[comit_node.alice]
host = "127.0.0.1"
config_file = "./api_tests/regtest/alice/comit_node.toml"

[comit_node.bob]
host = "127.0.0.1"
config_file = "./api_tests/regtest/bob/comit_node.toml"

[btsieve.main]
config_dir = "./api_tests/regtest/btsieve"
env = { RUST_LOG = "warn,btsieve=debug,warp=info" }

