ledgers = ["ethereum"]

[btsieve.main]
host = "127.0.0.1"
config_file = "./api_tests/regtest/btsieve/ethereum_only/btsieve.toml"

[btsieve.main.env]
RUST_LOG = "btsieve=debug,warp=debug,btsieve::api"
